print_freq: 100
output_dir: './logs'
checkpoint_freq: 12


sync_bn: True
find_unused_parameters: False

# Gradient Accumulation - set to 1 to disable, >1 to enable
gradient_accumulation_steps: 1

use_amp: False
scaler:
  type: GradScaler
  enabled: True


use_ema: False
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
